[package]
name = "myosotis"
version = "0.6.0"
edition = "2024"

[dependencies]
thiserror = "2"
sha2 = "0.10"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
clap = { version = "4", features = ["derive"] }